on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build, Lint, Test APK
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Make gradlew executable
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # Set up JDK 17
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # Cache Gradle dependencies
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper/
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      # Build project dependencies
      - name: Build Dependencies
        run: ./gradlew build -x lint -x test

      # Run Lint
      - name: Run Lint
        run: ./gradlew lint

      # Run Unit Tests
      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest

      # Build Debug APK
      - name: Build APK
        run: ./gradlew assembleDebug

      # Upload APK as artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk

#Upload test reports as artifact
      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: app/build/reports/tests/testDebugUnitTest/
